# Generated by Django 5.0.1 on 2024-02-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brytisen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activity_details',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='activity_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('UNDEFINED', 'Undefined'), ('TRENING', 'Trening'), ('FYLLA', 'Fylla'), ('VERV', 'Verv'), ('TOPPTUR', 'Topptur')], default='UNDEFINED', max_length=120),
        ),
    ]
