# Generated by Django 5.0.2 on 2024-03-13 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brytisen', '0002_favoritedactivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritedactivity',
            old_name='favorited_by_user',
            new_name='owner',
        ),
    ]
