# Generated by Django 5.0.2 on 2024-03-11 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brytisen', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='isReported',
        ),
        migrations.AlterField(
            model_name='reportedactivity',
            name='reported_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_reported_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReportedReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_reported_reviews', to=settings.AUTH_USER_MODEL)),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brytisen.review')),
            ],
            options={
                'verbose_name': 'Reported Review',
                'verbose_name_plural': 'Reported Reviews',
            },
        ),
    ]
