# Generated by Django 5.0.2 on 2024-03-13 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brytisen', '0003_rename_favorited_by_user_favoritedactivity_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritedactivity',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
