# Generated by Django 5.0.1 on 2024-02-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brytisen', '0003_activity_activity_rules_activity_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='isReported',
            field=models.BooleanField(null=True),
        ),
    ]
