# Generated by Django 4.1.4 on 2024-02-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brytisen', '0004_activity_isreported'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='tumbnail',
            field=models.FileField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
