# Generated by Django 4.1.4 on 2024-02-14 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brytisen', '0005_activity_tumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='tumbnail',
            new_name='thumbnail',
        ),
    ]
