# Generated by Django 5.0.2 on 2024-03-11 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brytisen', '0005_alter_review_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='isReported',
        ),
    ]
