# Generated by Django 5.0.2 on 2024-02-18 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brytisen', '0005_user'),
        ('brytisen', '0006_rename_tumbnail_activity_thumbnail'),
    ]

    operations = [
    ]
