# Generated by Django 5.0.3 on 2024-03-14 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brytisen', '0007_user_profilegradient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profileGradient',
            new_name='profile_gradient',
        ),
    ]
